### ISSUE TITLE
collection doesn't allow to add a grain

### ISSUE THREAD

**Issue by oec** [dwrensha/sandstorm-collections-app#12]
After installing the app from the app-store and creating a collection, nothing happens when I click on "Add grain...".

**Comment by dwrensha** [comment]
Hi!
You should see a "powerbox request" menu appear, giving you the option to select any of your grains to add to the collection.

What browser are you using? Do you see any errors in the browser debug console? Is this on Oasis or on a private Sandstorm instance?

**Comment by oec** [comment]
I attached the menu I see:

![screenshot 2016-11-28 at 17 13 16](https://cloud.githubusercontent.com/assets/200211/20675831/fd7ab42a-b58d-11e6-9a55-21cd0b0fadf4.png)

Neither clicking on "Add grain.." nor on "+" trigger any functionality, not even a message in the debug console.  Looking on the registered handlers for the corresponding button-tag it seems that the handler to tr.add-grains is "emptyFunction()", maybe that is a hint?

I use chrome on a chromebook (56.0.2920.0 dev (64-bit)) and the sandstorm-instance is private, using also  a private wildcard-certificate.

**Comment by dwrensha** [comment]
Is the certificate self-signed? Do you have any ad-blocking plugins enabled?

**Comment by oec** [comment]
The certificate is signed by a CA that is installed on the client side.  All other installed apps on our sandstorm-instance work flawlessly with this setup.  No ad-blocking plugin is enabled.

**Comment by dwrensha** [comment]
Do you see the same behavior in a Collections grain on Oasis? You can try through the demo: https://oasis.sandstorm.io/apps

**Comment by oec** [comment]
No, on the demo-site I actually _do_ get a "Powerbox request" menu.

**Comment by dwrensha** [comment]
Clicking on the "add grain" row initiates a `postMessage()` to the grain iframe's parent frame. The grain is served from your `WILDARD_HOST`, and the parent is server from `BASE_URL`. Is your `WILDCARD_HOST` not a subdomain of your `BASE_URL`? I vaguely remember hearing about other people getting in trouble when that was the case. @paulproteus probably knows more than I do about such problems.

**Comment by dwrensha** [comment]
(oops, I intially tagged the wrong person for @paulproteus)

**Comment by dwrensha** [comment]
I expect that the (+) button in the Wekan app under "members" will also not work for you on your private server, because it uses a similar powerbox `postMessage()`.

**Comment by oec** [comment]
these are our settings in the sandstorm.conf:

```
BASE_URL=https://foo.bar.com
WILDCARD_HOST=sandstorm-*.foo.bar.com:443
```

Semantically, WILDCARD_HOST refers to subdomains underneath of BASE_URL.  Maybe there is a formal mismatch?

Indeed, in the Wekan app, I can not add members.

**Comment by dwrensha** [comment]
Does it help to remove the ":443" from the `WILDCARD_HOST`?

**Comment by oec** [comment]
*Bazinga*, that worked indeed!  I can now add grains to the collection!

Thanks for the tip!

PS: I blindly followed someone's HOWTO on how to setup a self-hosted, wildcarded sandstorm instance and, IIRC, providing the port on the WILDCARD_HOST was part of it.

**Comment by dwrensha** [comment]
Cool! I'm happy to have helped.

If you happen to still have a link to that tutorial, I'd be interested in seeing it.

**Comment by paulproteus** [comment]
Thanks to both of you for looking into this and discovering the solution, and I'm looking forward to making it harder to make these kinds of mistakes.

**Comment by oec** [comment]
I'm can't recall the links to the various resources/howtos I used other than the sandstorm-docs - the links I get from google right now aren't the ones I used.

However, actually, it might very well be I was confused about this (from the [sandstorm FAQ](https://docs.sandstorm.io/en/latest/administering/faq/#why-do-i-see-an-error-when-i-try-to-launch-an-app-even-when-the-sandstorm-interface-works-fine)):

> Make sure the WILDCARD_HOST has valid syntax. In the Sandstorm config file (typically /opt/sandstorm/sandstorm.conf), look for the WILDCARD_HOST config item. Note that this should not have a protocol as part of it but does need a port number _**if BASE_URL specifies a port number**_. A valid line might be:
`WILDCARD_HOST=*.yourname.sandcats.io:6080`

(highlight is mine) I probably ignored the highlighted part and simply extrapolated from ":6080" to ":443".
