### ISSUE TITLE
UiView.PowerboxTag.title is not filled in when calling offer()

### ISSUE THREAD

**Issue by kentonv** [dwrensha/sandstorm-collections-app#2]
Currently Sandstorm erroneously ignores this title, and actually assigns _no_ title. In some contexts, the upstream title ends up being used instead, but in others nothing is displayed.

I'm fixing the Sandstorm end, but the collections app needs a fix as well.

**Comment by kentonv** [comment]
This fixes the Sandstorm side: https://github.com/sandstorm-io/sandstorm/pull/2260/commits/1ab3403bd9f517c46d169f0430d66453e3d0a100

**Comment by dwrensha** [comment]
I think this is fixed in 7129ce9ebb6cf9ed5fcbd3588cf98937557ebe28.

>  in others nothing is displayed.

I was unable to get this to happen. Can you be more specific about how to reproduce an empty title?
